version: '3.1'

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root123
    ports:
      - 5432:5432
    volumes:
      - /Users/timgluz/workspace/lmweb/db:/var/lib/postgresql/
